project_id = "yzqwmxffjufefocgkevz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation_enabled = true

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54329

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"


[functions.historical-data-generator]
verify_jwt = false

[functions.load-test-generator]
verify_jwt = false

[functions.process-automations]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.whatsapp-connect]
verify_jwt = false

[functions.whatsapp-status]
verify_jwt = false

[functions.evolution-instance-manager]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.test-evolution-api]
verify_jwt = false

[functions.whatsapp-automations]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-phone-code]
verify_jwt = false

[functions.send-review-request]
verify_jwt = false

[functions.subscription-automations]
verify_jwt = false

[functions.whatsapp-auto-configurator]
verify_jwt = false

[functions.whatsapp-automation-scheduler]
verify_jwt = false

[functions.whatsapp-reminders]
verify_jwt = false

[functions.generate-session-link]
verify_jwt = false

[functions.validate-session]
verify_jwt = false

[functions.generate-anonymous-session]
verify_jwt = false